MISP/misp-taxonomies

README.md
command line example starting on line 76 missed a step, and if followed, results in the machinetag.json file being created in the wrong directory
=> fix missing step in command line example

PAP/machinetag.json
When sharing an event it should be possible to let the receiving parties know, whether there is any restrictions in using the shared information or not. This should for example keep a receiving party from giving away information to a possible attacker (e.g. by pinging the target or conduction online checks).
=> Permissible Actions Protocol ("PAP")

MANIFEST.json, README.md, domain-abuse/machinetag.json
taxonomy to tag domain names used for cybercrime. 
Written at TF-CSIRT hackathon by @sykaeh & @mausding from @switch-ch
=> Domain name abuse taxonomy

MANIFEST.json, misp-galaxy/machinetag.json, tools/generator/misp-galaxy.py
This pull request bridges the future implementation of the galaxy with the taxonomies.
- a script to convert it automatically
- misp-galaxy namespace
- updated manifest file and machinetag.json
Limitations:
- version numbers are not taken into account when generating a new machinetag.json: the cause is that multiple galaxy elements have their own version number, but the taxonomy has only one. 
- synonyms are ignored: as discussed this was the preferred approach that would have the least complexity when the galaxy is integrated with MISP in a more advanced way. 
Please take the time to review and test with MISP before merging.
=> Galaxy elements as taxonomies

diamond-model/machinetag.json
Hi,
I quickly created the taxonomy describing the Diamond Model for Intrusion Analysis, definition of the fields are the official ones from the original paper
http://www.activeresponse.org/wp-content/uploads/2013/07/diamond.pdf
Not sure if possible to add this as source in the json as well.
Pasquale
=> adding diamond model taxonomy

kill-chain/machinetag.json
The official term (see. http://www.lockheedmartin.com/us/what-we-do/aerospace-defense/cyber/cyber-kill-chain.html) relies on the American/Oxford spelling.
=> Typo fix: replaces weaponiSation by weaponiZation

tools/machinetag.py
Previously, machinetag could only be run from the `tools/` directory - which is a bit silly.
That's fixed now :)
=> Update machinetag to allow running from any directory

analyst-assessment/machinetag.json
Here is a modified version of the analyst assessment centred on the analyst's skills. I remove the part about the analysis because I think this should be put into a new taxonomy related to analyses.
=> New items to analyst assessment, removal of analysis-related items

cssa
Used by CSSA e.V. members to add the Class (quality of the data: High_class, Vetted, Unvetted) and the Origin of the data.
=> CSSA Taxonomy

misp/machinetag.json
It is useful to label automatically and semi-automatically generated information accordingly as such. For this purpose, we propose the `misp:automation-level` predicate:
- `unsupervised`for data generated automatically without human verification
- `reviewed` for data generated automatically but verified by a human
- `manual` for data that is the output of human analysis
This change was co-designed with @h122015 and @amuehlem.
=> Add automation-level predicate to misp taxonomy

misp/machinetag.json
Setting multiple values of this predicate would be contradictory.
This was missed in the previous pull req, apologies.
=> Set exclusive flag on misp:automation-level predicate

MANIFEST.json, README.md, dcso-sharing/machinetag.json
We would like to contribute the DCSO Sharing Taxonomy. It is used to classify events that are shared within the Sharing Group.
=> DCSO Sharing Taxonomy added

ransomware/machinetag.json
**Date:** 2019-04-11
**Author:** SwitHak
**Purpose:** Add 3 meta tag to be able to give specification of extensions usage:  
1. ransomware-appended-extension
-> This is the extension added by the ransomware to the files.
2. ransomware-encrypted-extensions",
-> This is the list of extensions that will be encrypted by the ransomware. Beware to keep the order.
3. ransomware-excluded-extensions",
-> This is the list of extensions that will not be encrypted by the ransomware. Beware to keep the order.
If I missed something, tell me through the PR or via Twitter: @SwitHak
=> Update Ransomware Taxonomy

retention/machinetag.json
This retention taxonomy can be used to tag events and attributes that need to be expired after a certain amount of time. A companion MISP API scipt can clear the appropriate to_ids flags when the tagged IOC's become expired.
See also https://github.com/MISP/MISP/pull/4661
=> Retention taxonomy

infoleak/machinetag.json
What do you think? Should we add a distinction between ipv4 and ipv6? Would it make sense for mac address?
=> chg: [infoleak] Added IP address tag value

iep2-policy-reference/machinetag.json, iep2-policy/machinetag.json, iep2-reference/machinetag.json
Hi,
I'm one of the IEP co-chairs, and we've just had IEP 2.0 approved by the FIRST board. We're in the process of getting IEP 2.0 website created (it will live at https://www.first.org/iep/), but it's not quite online yet.
As MISP had an IEP 1.0 implementation we wanted to help out the community and do one for IEP 2.0 as well. IEP 2.0 has two objects, the IEP Policy object and the IEP 2.0 Policy Reference object, and as such this pull request contains those two objects as well. 
There is one bit I'd like special review on, and that is the fact that I've used a JSON number for the iep_version tag. The reason is that IEP 2.0 specifies the iep_version must be a JSON number. We'd like to check that this won't break MISP... as we're not sure if MISP will handle numerical values in the tags. …
=> Adding IEP 2.0

DFRLab-dichotomies-of-disinformation/machinetag.json
New disinformation taxonomy courtesy the Atlantic Council DFRLab.  All definitions are copied from their source material here: https://github.com/DFRLab/Dichotomies-of-Disinformation
Probably some minor revisions needed to make the tags less verbose.
=> new: [taxonomy] add "DFRLab Dichotomies of Disinformation"

cytomic_orion/machinetag.json
Taxonomy that is used to indicate what needs to happen with attributes upload/delete from Cytomic Orion.
=> Taxonomy to describe desired actions for Cytomic Orion

MANIFEST.json, README.md, trust/machinetag.json
It is used to describe what is known to be good, instead of the bad stuff.
This goes along what I described during my talk at CanSecWest: http://io.libio.so/stricaud-cansec2020.pdf 
Instead of using attributes to search for the bad, we use attributes to filter out the good things, similar to a whitelist, except it leverages all MISP features.
=> Adding the Trust Taxonomy

phishing/machinetag.json
Suggestion for another phishing attack related directors and executive employees, usually named also as Ceo Spoofing attack.
=> Proposal for whaling phishing

README.md, thales-group-taxonomy/machinetag.json
Dear all,
As Alexandre suggest (https://github.com/thalesgroup-cert/Thalesgroup-misp-taxonomy/issues/2), we are more than happy to contribute!
For the moment the taxonomy is called "thales-group-taxonomy".
However, feel free to change it to "thales-group" if you need this taxonomy to be more consistent with the others.
Thank you in advance!
=> Thales Group taxonomy to contribute for the official MISP taxonomy repository

fr-classif/machinetag.json
L'IGI1300 décrit 2 niveaux de classification : Secret et Très Secret. Les informations ainsi protégées sont dites classifiées. L'IGI1300 (§1.3.2) précise également qu'il existe une mention de protection dite "Diffusion Restreinte" pour des informations non classifiées. Or, les informations non classifiées et non protégées par la mention Diffusion Restreinte sont dites "Non protégées".
Par cohérence avec les timbres "Secret" et "Très Secret", la mention "Non protégé" est proposée au masculin.
=> Correction de "Non classifiée" vers "Non protégé"

state-responsibility/README.md, state-responsibility/machinetag.json
The taxonomy is inspired on an article from Jason Healey in the Atlantic Council [Beyond Attribution: Seeking National Responsibility for Cyber Attacks](https://www.atlanticcouncil.org/wp-content/uploads/2012/02/022212_ACUS_NatlResponsibilityCyber.PDF).
=> Add state-responsibility

course-of-action/machinetag.json
Hi,
I'm on a use case where we want to search attributes regularly on historical data as some kind of default action for new attributes. On some rare cases we want to exclude specific (noisy) attributes from that default process.
The Course of Action taxonomy would match quiet good here but I would need a specific tag to exclude that noisy IOCs.
What do you think about this change?
Regards,
Hendrik
=> Add 'course-of-action:passive=nodiscover'

dark-web/machinetag.json
The Joint Research Centre (JRC) has worked on the extension of the existent dark-web taxonomy now supporting the presence of ransomware groups on the darknet.
=> Dark-Web Ransomware support 

MANIFEST.json, README.md, priority-level/machinetag.json, summary.md
Looks like they changed the doc location
=> chg: [priority-taxonomy] update reference url

misp/machinetag.json
Mainly copied from dcso taxonomy, just very minor changes from myself.
=> chg: [misp:event-type] Add description of the tags

nis2/machinetag.json
This is a somewhat major update (but based on the "official" pdf)  so reject the pull request if you wish,no problem.!
Added some sectors (and subsectors in a similar fashion as the ones already set) according to this document (see annex I and II) Directive (EU) 2022/2555 https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32022L2555. Added annex II sectors because they also appear in some ENISA brochures. 
The subsectors contain few examples of entities as in version3 of this taxonomy file. I did not update the "entities" in the taxonomy because we would have to add many items and it is better to use another taxonomy (in the nis2 document they already mention NACE classification for that).
=> nis2: add more sectors and subsectors from nis2.pdf

PAP/machinetag.json
I propose to remove Virustotal as a passive lookup tool, since Virustotal actively scans an IP address if it is not already present in its database. Hence this action breaks the PAP:AMBER restriction that you are not allowed initiate contact with the as PAP:AMBER classified system.
=> Adapt PAP:AMBER description
