first_csirt_case_classification/README.md, first_csirt_case_classification/machinetag.json
Introducing a new taxonomie that is created by FIRST (https://www.first.org/_assets/resources/guides/csirt_case_classification.html) with different types of incidents etc.
Kudos to  Dustin Schieber dschiebe@cisco.com  Gavin Reid gavreid@cisco.com for creating it.
=> CSIRT Case Classification (Example for Enterprise CSIRT)

malware/README.md, malware/machinetag.json
Comments / Further points to be mentioned welcome
=> first shot of malware classification

README.md
=> How to write your private taxonomy

README.md, information-security-indicators/machinetag.json, tools/machinetag.py
Based on http://www.etsi.org/deliver/etsi_gs/ISI/001_099/00101/01.01.02_60/gs_ISI00101v010102p.pdf
=> Add the Information Security Indicators taxonomy

tools/machinetag.py
solves the problem to update the list constantly.
The previous list also contained typo's and didn't include some entries.
=> dynamically build taxonomies list

README.md, stealth-malware/README.md, stealth-malware/machinetag.json
See https://vxheaven.org/lib/pdf/Introducing%20Stealth%20Malware%20Taxonomy.pdf
=> Add Stealth Malware Taxonomy as defined by Joanna Rutkowska

README.md
with regards from the MISP Training in ZRH :-)
=> Fixed some broken links in README.md

README.md, stix-ttp/machinetag.json
The STIX-TTP taxonomy follows the STIX model to handle the classification of event TTPs.
This version covers both **Victim Trageting by Sector** and **Victim Targeting by Information Type**.
=> Introducing STIX-TTP Taxonomy

MANIFEST.json, passivetotal/machinetag.json
it's only the basic tags, but that's all we can really do :cactus:
=> Added passivetotal tags for #30.

MANIFEST.json, accessnow/machinetag.json
Just waiting for review before merging
=> [WIP] Add assessnow taxonomy

README.md, binary-class/README.md, binary-class/machinetag.json
For #59. 
Tags for good / bad / unknown binaries
=> Basic binary taxonomy

CERT-XLM/machinetag.json, MANIFEST.json
Taxonomie for the Excellium Services CERT-XLM.
=> Add CERT-XLM taxonomie

eu-nis-sector-and-subsectors
Taxonomy created that includes the sectors and sub sectors according to the NIS Directive. 
Adding the sub sectors allows creation of using more detailed tags. 
Content is strictly based on the directive requirements.
=> eu-nis-sector-and-subsectors

infoleak/machinetag.json
Signed-off-by: Terrtia <or1994@hotmail.fr>
=> infoleak taxonomy, add ail tags

maec-delivery-vectors/machinetag.json, maec-malware-behavior/machinetag.json, maec-malware-capabilities/machinetag.json, maec-malware-capabilties/machinetag.json, maec-malware-obfuscation-methods/machinetag.json
Following taxonomies updated 👍 
- Delivery vectors
- Behavior
- Capabilities
- Obfuscation methods
=> Updated MAEC 5.0 taxonomies for malware

infoleak/machinetag.json
infoleak,
add predicates:
- type of submission
- output format
- test
=> infoleak, add type of submission, output format and test predicates

infoleak/machinetag.json
add binary and hexadecimal for encoded strings
=> chg: [infoleak] add binary and hexadecimal

infoleak/machinetag.json
=> chg: [infoleak] add iban

MANIFEST.json, README.md, file-type/machinetag.json
A taxonomy for known file types
=> [add]  new file-type taxonomy

MANIFEST.json, access-method/machinetag.json, approved-category-of-action/machinetag.json, cccs/machinetag.json, interception-method/machinetag.json, tools/alfred_taxonomies.py
=> new: CCCS taxonomies, first batch

use-case-applicability/machinetag.json
Added machinetag.json File for Use Case Applicability categories, described in https://github.com/d3sre/Use_Case_Applicability/blob/master/UseCaseApplicability-Paper.pdf
=> added use case applicability machinetag.json

common-taxonomy/machinetag.json
The Common Taxonomy for Law Enforcement and The National Network of CSIRTs bridges the gap between the CSIRTs and international Law Enforcement communities by adding a legislative framework to facilitate the harmonisation of incident reporting to competent authorities, the development of useful statistics and sharing information within the entire cybercrime ecosystem.
=> Common Taxonomy for LE and CSIRTs (Cybercrime)

infoleak/machinetag.json
chg: [infoleak] add pgp-public-key-block, pgp-signature
=> chg: [infoleak] add pgp-public-key-block, pgp-signature

dark-web/machinetag.json
Not "necessary" but do complete the darkweb taxonomy
=> Scam, Software, Escrow and a few definitions

dark-web/machinetag.json
added : ddos services, politics, whistleblower
=> add: [darkweb] ddos services, politics, whistleblower

dark-web/machinetag.json
Reordering + adding few tags.
To be reviewed before merge. No incentive for a quick merge.
=> add: [tags] crypto, contreband, etc.

phishing/machinetag.json
- based on:
- Cialdini's principal of influence,
- Graggs's psychological triggers,
- Stajano's principles of scams,
- see associated paper: Ferreira & al. DOI: 10.1007/978-3-319-20376-8_4
=> chg: [phishing] add principles of persuasions

MANIFEST.json, course-of-action/machinetag.json
Added Course of Action A Course Of Action analysis considers six potential courses of action for the development of a cyber security capability.
=> Course of Action

cssa/machinetag.json
=> add "report"

infoleak/machinetag.json
=> chg: [infoleak] add public-key

diamond-model/machinetag.json
=> Correct Diamond model taxonomy description

MANIFEST.json, README.md, trust/machinetag.json
This PR introduces the Trust taxonomy which defines how a certain attribute can be trusted.
=> Trust Taxonomy

extended-event/machinetag.json
WIP First proposal for extended-event taxonomy
=> new: [extended-event] first proposal

misinformation-website-labels/machinetag.json
A classification to help identify types of misinformation among websites.
Source : False, Misleading, Clickbait-y, and/or Satirical 'News' Sources by Melissa Zimdars 2016
=> new: [misinformation-website-labels] first proposal

threatmatch-alert-types/README.md, threatmatch-alert-types/machinetag.json, threatmatch-incident-types/README.md, threatmatch-incident-types/machinetag.json, threatmatch-malware-types/README.md, threatmatch-malware-types/machinetag.json, threatmatch-sectors/README.md, threatmatch-sectors/machinetag.json
Request to import 4 taxonomies from ThreatMatch useful for alert and malware definitions and sectors.
=> ThreatMatch taxonomies

rsit/machinetag.json
Latest version from https://github.com/enisaeu/Reference-Security-Incident-Taxonomy-Task-Force/blob/master/working_copy/machinev1
=> rsit: Update to version 1002

vmray/machinetag.json
Introducing mappings of VMRay Verdicts and scores to Triple Tags.
=> add VMRay taxonomies

rsit/machinetag.json
v1.3 was released in May: https://github.com/enisaeu/Reference-Security-Incident-Taxonomy-Task-Force/releases/tag/v1.3
including the version tag fix
(https://github.com/enisaeu/Reference-Security-Incident-Taxonomy-Task-Force/pull/109)
=> update RSIT to version 1003

MANIFEST.json, unified-kill-chain/machinetag.json
Made a taxonomy out of the Unified Kill Chain, a more refined version of the Kill Chain. You can refer to https://www.unifiedkillchain.com/ for more information.
=> Initial commit of Unified Kill Chain.

README.md
=> Rephrase machine tags sentence in README.md (#221)

GrayZone/machinetag.json
GrayZone of Active Defense, originaly published by Washington University, v2 created and updated by DCG420
=> Add machinetag.json of GrayZone Taxonomy

MANIFEST.json, pyoti/machinetag.json
taxonomy to use to apply automated enrichment tags when using PyOTI
=> adding PyOTI enrichment taxonomy

MANIFEST.json, pyoti/machinetag.json
Adding a few domain-based reputation block list entries.
=> Pyoti taxonomy v2

file-type/machinetag.json
Added xlsm file type to file-type taxonomy
=> Added xlsm file type to file-type taxonomy 

file-type/machinetag.json
=> Added to File Type taxonomy

thales_group/machinetag.json
[Error Fix] Modify ISAC Tag to Aviation ISAC Tag
=> [Error Fix] Modify ISAC Tag to A_ISAC Tag

MANIFEST.json, sentinel-threattype/machinetag.json
Taxonomy in support of integrating MISP with Sentinel. Allows to set the "threatType values".
=> Sentinel indicator threat types

dark-web/machinetag.json
The Joint Research Centre (JRC) has worked on the extension of the existent dark-web taxonomy. Now entities found in dark-web services and its properties are included.
=> Expanded Dark-Web taxonomy developed by the Joint Research Centre (JRC)

cryptocurrency-threat/machinetag.json
Added new threat related to crypto currencies.
=> Update Cryptocurrency Threat Taxonomy

runtime-packer/machinetag.json
Added various packer names to `runtime-packers/machinetag.json`.
=> Improved runtime-packers

nis2/machinetag.json
Typo in digital infrastructure
=> nis2: minor typo

nis2/machinetag.json
=> nis2: (patch) few minor typos
